"""
Generate market/{market_id}/  with separate index.html, style.css, script.js
for every product in the database.

Run standalone:  python generate_market.py
Called by app.py after every product insert.
"""
import os, json
from database import get_all_products, get_product

BASE       = os.path.dirname(os.path.abspath(__file__))
MARKET_DIR = os.path.join(BASE, 'market')
SERVER     = ''  # relative URLs work with any server/port

# ── Category illustrations (SVG paths) ────────────────────────────────────────
_CAT_ART = {
'Language Model': '''
  <circle cx="400" cy="200" r="60" fill="none" stroke="rgba(255,255,255,.35)" stroke-width="2"/>
  <circle cx="200" cy="120" r="18" fill="rgba(255,255,255,.3)"/>
  <circle cx="600" cy="100" r="22" fill="rgba(255,255,255,.25)"/>
  <circle cx="160" cy="280" r="15" fill="rgba(255,255,255,.2)"/>
  <circle cx="620" cy="300" r="20" fill="rgba(255,255,255,.28)"/>
  <circle cx="340" cy="90"  r="12" fill="rgba(255,255,255,.2)"/>
  <line x1="400" y1="200" x2="200" y2="120" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
  <line x1="400" y1="200" x2="600" y2="100" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
  <line x1="400" y1="200" x2="160" y2="280" stroke="rgba(255,255,255,.15)" stroke-width="1.5"/>
  <line x1="400" y1="200" x2="620" y2="300" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
  <line x1="200" y1="120" x2="340" y2="90"  stroke="rgba(255,255,255,.12)" stroke-width="1"/>
  <text x="400" y="210" font-family="serif" font-size="42" text-anchor="middle" fill="rgba(255,255,255,.9)">🧠</text>
  <text x="250" y="200" font-family="monospace" font-size="11" fill="rgba(255,255,255,.4)">{"role":"user"}</text>
  <text x="480" y="240" font-family="monospace" font-size="11" fill="rgba(255,255,255,.4)">tokens: 4096</text>''',

'Image Generation': '''
  <rect x="130" y="80"  width="180" height="120" rx="8" fill="rgba(255,100,200,.3)" stroke="rgba(255,255,255,.2)" stroke-width="1"/>
  <rect x="320" y="60"  width="200" height="140" rx="8" fill="rgba(100,200,255,.3)" stroke="rgba(255,255,255,.2)" stroke-width="1"/>
  <rect x="530" y="90"  width="150" height="110" rx="8" fill="rgba(200,255,100,.25)" stroke="rgba(255,255,255,.2)" stroke-width="1"/>
  <circle cx="280" cy="240" r="70" fill="rgba(255,180,50,.25)" stroke="rgba(255,255,255,.15)" stroke-width="1"/>
  <circle cx="500" cy="270" r="55" fill="rgba(100,100,255,.25)" stroke="rgba(255,255,255,.15)" stroke-width="1"/>
  <text x="400" y="195" font-family="serif" font-size="50" text-anchor="middle" fill="rgba(255,255,255,.9)">🎨</text>
  <text x="400" y="320" font-family="sans-serif" font-size="12" text-anchor="middle" fill="rgba(255,255,255,.4)">2048 × 2048px · CLIP 96.8%</text>''',

'Code Generation': '''
  <rect x="100" y="60" width="600" height="280" rx="12" fill="rgba(0,0,0,.45)" stroke="rgba(255,255,255,.15)" stroke-width="1.5"/>
  <rect x="100" y="60" width="600" height="32" rx="12" fill="rgba(255,255,255,.08)"/>
  <circle cx="128" cy="76" r="7" fill="#ff5f57"/><circle cx="152" cy="76" r="7" fill="#ffbd2e"/><circle cx="176" cy="76" r="7" fill="#28c941"/>
  <text x="136" y="108" font-family="monospace" font-size="13" fill="#a78bfa">def </text>
  <text x="175" y="108" font-family="monospace" font-size="13" fill="#34d399">analyze</text>
  <text x="257" y="108" font-family="monospace" font-size="13" fill="rgba(255,255,255,.8)">(data):</text>
  <text x="150" y="132" font-family="monospace" font-size="13" fill="rgba(255,255,255,.5)">  # Generated by AI · 13B params</text>
  <text x="150" y="156" font-family="monospace" font-size="13" fill="#fbbf24">  result </text>
  <text x="237" y="156" font-family="monospace" font-size="13" fill="rgba(255,255,255,.7)">= process(data)</text>
  <text x="150" y="180" font-family="monospace" font-size="13" fill="#a78bfa">  return </text>
  <text x="222" y="180" font-family="monospace" font-size="13" fill="rgba(255,255,255,.7)">result</text>
  <text x="150" y="210" font-family="monospace" font-size="11" fill="rgba(255,255,255,.25)">  # Tests: 847 passed · Coverage 94.7%</text>''',

'Voice & Audio': '''
  <g transform="translate(0,20)">
  <path d="M80,200 Q120,130 160,200 Q200,270 240,200 Q280,130 320,200 Q360,270 400,200 Q440,130 480,200 Q520,270 560,200 Q600,130 640,200 Q680,270 720,200" fill="none" stroke="rgba(255,255,255,.5)" stroke-width="2.5"/>
  <path d="M80,200 Q120,155 160,200 Q200,245 240,200 Q280,155 320,200 Q360,245 400,200 Q440,155 480,200 Q520,245 560,200 Q600,155 640,200 Q680,245 720,200" fill="none" stroke="rgba(255,255,255,.25)" stroke-width="1.5"/>
  </g>
  <text x="400" y="230" font-family="serif" font-size="55" text-anchor="middle" fill="rgba(255,255,255,.9)">🎙️</text>
  <text x="400" y="330" font-family="sans-serif" font-size="12" text-anchor="middle" fill="rgba(255,255,255,.4)">40+ Languages · 99.1% Similarity</text>''',

'Computer Vision': '''
  <rect x="120" y="70" width="560" height="280" rx="6" fill="rgba(0,0,0,.3)" stroke="rgba(255,255,255,.2)" stroke-width="1"/>
  <rect x="180" y="95"  width="120" height="130" rx="3" fill="none" stroke="#34d399" stroke-width="2" stroke-dasharray="6,3"/>
  <rect x="340" y="110" width="90"  height="100" rx="3" fill="none" stroke="#fbbf24" stroke-width="2" stroke-dasharray="6,3"/>
  <rect x="460" y="80"  width="160" height="180" rx="3" fill="none" stroke="#f87171" stroke-width="2" stroke-dasharray="6,3"/>
  <text x="180" y="91"  font-family="monospace" font-size="10" fill="#34d399">person 98.2%</text>
  <text x="340" y="106" font-family="monospace" font-size="10" fill="#fbbf24">car 95.1%</text>
  <text x="460" y="76"  font-family="monospace" font-size="10" fill="#f87171">truck 91.7%</text>
  <text x="400" y="310" font-family="sans-serif" font-size="12" text-anchor="middle" fill="rgba(255,255,255,.4)">10,000+ Classes · 120 FPS · 96.1% mAP</text>''',

'Healthcare AI': '''
  <path d="M80,220 L160,220 L200,140 L240,300 L280,180 L320,250 L360,200 L400,200 L440,120 L480,280 L520,170 L560,220 L720,220" fill="none" stroke="rgba(255,100,100,.7)" stroke-width="2.5"/>
  <path d="M350,140 L350,270 M285,205 L415,205" stroke="rgba(255,255,255,.5)" stroke-width="4" stroke-linecap="round"/>
  <circle cx="400" cy="205" r="55" fill="none" stroke="rgba(255,255,255,.15)" stroke-width="1.5"/>
  <text x="400" y="330" font-family="sans-serif" font-size="12" text-anchor="middle" fill="rgba(255,255,255,.4)">97.3% Accuracy · FDA-compliant</text>''',

'Financial AI': '''
  <polyline points="100,300 160,260 220,280 280,200 340,230 400,150 460,180 520,120 580,160 640,100 700,130" fill="none" stroke="rgba(52,211,153,.7)" stroke-width="2.5"/>
  <polyline points="100,300 160,260 220,280 280,200 340,230 400,150 460,180 520,120 580,160 640,100 700,130 700,350 100,350" fill="rgba(52,211,153,.1)"/>
  <rect x="140" y="230" width="16" height="70"  fill="rgba(52,211,153,.5)"/>
  <rect x="200" y="200" width="16" height="100" fill="rgba(248,113,113,.5)"/>
  <rect x="260" y="160" width="16" height="140" fill="rgba(52,211,153,.5)"/>
  <rect x="320" y="180" width="16" height="120" fill="rgba(52,211,153,.5)"/>
  <text x="400" y="95" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(52,211,153,.6)">+18.4% ↑ BULLISH SIGNAL</text>''',

'Robotics': '''
  <circle cx="400" cy="140" r="55" fill="rgba(255,255,255,.12)" stroke="rgba(255,255,255,.3)" stroke-width="2"/>
  <circle cx="400" cy="140" r="20" fill="rgba(255,255,255,.2)"/>
  <line x1="400" y1="195" x2="400" y2="270" stroke="rgba(255,255,255,.4)" stroke-width="8" stroke-linecap="round"/>
  <line x1="400" y1="220" x2="310" y2="270" stroke="rgba(255,255,255,.35)" stroke-width="7" stroke-linecap="round"/>
  <line x1="400" y1="220" x2="490" y2="270" stroke="rgba(255,255,255,.35)" stroke-width="7" stroke-linecap="round"/>
  <circle cx="310" cy="278" r="14" fill="rgba(255,255,255,.2)"/>
  <circle cx="490" cy="278" r="14" fill="rgba(255,255,255,.2)"/>
  <text x="400" y="148" font-family="serif" font-size="26" text-anchor="middle" fill="rgba(255,255,255,.9)">🤖</text>
  <text x="400" y="330" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">50+ Robot Platforms · 98.7% Task Completion</text>''',

'Cybersecurity': '''
  <path d="M400,70 L500,110 L500,210 Q500,290 400,340 Q300,290 300,210 L300,110 Z" fill="rgba(255,255,255,.1)" stroke="rgba(255,255,255,.35)" stroke-width="2"/>
  <path d="M400,100 L470,130 L470,210 Q470,270 400,310 Q330,270 330,210 L330,130 Z" fill="rgba(255,255,255,.08)" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
  <text x="400" y="235" font-family="serif" font-size="55" text-anchor="middle" fill="rgba(255,255,255,.9)">🔒</text>
  <text x="400" y="330" font-family="monospace" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">99.98% Detection · &lt;0.01% FPR</text>''',

'Data Analysis': '''
  <rect x="130" y="290" width="40" height="60"  fill="rgba(255,255,255,.4)"/>
  <rect x="190" y="230" width="40" height="120" fill="rgba(255,255,255,.35)"/>
  <rect x="250" y="190" width="40" height="160" fill="rgba(255,255,255,.45)"/>
  <rect x="310" y="150" width="40" height="200" fill="rgba(255,255,255,.5)"/>
  <rect x="370" y="210" width="40" height="140" fill="rgba(255,255,255,.35)"/>
  <rect x="430" y="170" width="40" height="180" fill="rgba(255,255,255,.42)"/>
  <rect x="490" y="120" width="40" height="230" fill="rgba(255,255,255,.55)"/>
  <rect x="550" y="180" width="40" height="170" fill="rgba(255,255,255,.38)"/>
  <polyline points="150,280 210,220 270,180 330,140 390,200 450,160 510,110 570,170" fill="none" stroke="#34d399" stroke-width="2.5"/>
  <text x="400" y="90" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">1M+ rows · 97.8% anomaly detection</text>''',

'Biological': '''
  <path d="M320,60 Q360,130 320,200 Q280,270 320,340" fill="none" stroke="rgba(255,255,255,.55)" stroke-width="3"/>
  <path d="M480,60 Q440,130 480,200 Q520,270 480,340" fill="none" stroke="rgba(255,255,255,.55)" stroke-width="3"/>
  <line x1="320" y1="100" x2="480" y2="100" stroke="rgba(255,255,255,.4)" stroke-width="2"/>
  <line x1="323" y1="140" x2="477" y2="140" stroke="rgba(255,255,255,.35)" stroke-width="2"/>
  <line x1="320" y1="180" x2="480" y2="180" stroke="rgba(255,255,255,.4)" stroke-width="2"/>
  <line x1="323" y1="220" x2="477" y2="220" stroke="rgba(255,255,255,.35)" stroke-width="2"/>
  <line x1="320" y1="260" x2="480" y2="260" stroke="rgba(255,255,255,.4)" stroke-width="2"/>
  <line x1="323" y1="300" x2="477" y2="300" stroke="rgba(255,255,255,.35)" stroke-width="2"/>
  <text x="400" y="390" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">20B params · 99.9% variant calling</text>''',

'Space Tech': '''
  <circle cx="400" cy="200" r="90" fill="rgba(30,60,120,.5)" stroke="rgba(100,150,255,.4)" stroke-width="2"/>
  <ellipse cx="400" cy="200" rx="160" ry="45" fill="none" stroke="rgba(255,255,255,.25)" stroke-width="1.5"/>
  <ellipse cx="400" cy="200" rx="220" ry="60" fill="none" stroke="rgba(255,255,255,.12)" stroke-width="1"/>
  <circle cx="400" cy="200" r="40" fill="rgba(50,100,200,.4)"/>
  <circle cx="250" cy="165" r="8" fill="rgba(255,255,255,.6)"/>
  <circle cx="150" cy="90"  r="3" fill="rgba(255,255,255,.5)"/>
  <circle cx="650" cy="110" r="4" fill="rgba(255,255,255,.5)"/>
  <circle cx="580" cy="280" r="3" fill="rgba(255,255,255,.4)"/>
  <text x="400" y="370" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">94% prediction · 72hr forecast</text>''',

'Climate & Environment': '''
  <circle cx="400" cy="190" r="110" fill="rgba(30,100,60,.4)" stroke="rgba(100,220,150,.4)" stroke-width="2"/>
  <path d="M290,150 Q360,100 430,140 Q500,180 550,150 Q550,260 400,290 Q250,270 290,150" fill="rgba(50,150,100,.4)"/>
  <path d="M270,200 Q320,180 370,200 Q420,220 470,200 Q500,200 530,210 A130,130 0 0,1 270,200" fill="rgba(30,80,180,.35)"/>
  <path d="M400,80 Q390,130 400,150 Q410,130 400,80" fill="rgba(50,200,100,.6)"/>
  <path d="M370,95 Q365,125 375,140 Q385,125 370,95" fill="rgba(50,200,100,.4)"/>
  <text x="400" y="370" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">10km resolution · 92% accuracy</text>''',

'Human Services': '''
  <circle cx="280" cy="140" r="30" fill="rgba(255,255,255,.2)" stroke="rgba(255,255,255,.35)" stroke-width="1.5"/>
  <circle cx="400" cy="120" r="36" fill="rgba(255,255,255,.28)" stroke="rgba(255,255,255,.4)" stroke-width="2"/>
  <circle cx="520" cy="140" r="30" fill="rgba(255,255,255,.2)" stroke="rgba(255,255,255,.35)" stroke-width="1.5"/>
  <text x="280" y="152" font-family="serif" font-size="28" text-anchor="middle" fill="rgba(255,255,255,.8)">👤</text>
  <text x="400" y="134" font-family="serif" font-size="34" text-anchor="middle" fill="rgba(255,255,255,.9)">👤</text>
  <text x="520" y="152" font-family="serif" font-size="28" text-anchor="middle" fill="rgba(255,255,255,.8)">👤</text>
  <line x1="310" y1="145" x2="364" y2="135" stroke="rgba(255,255,255,.3)" stroke-width="1.5"/>
  <line x1="436" y1="135" x2="490" y2="145" stroke="rgba(255,255,255,.3)" stroke-width="1.5"/>
  <line x1="280" y1="170" x2="280" y2="250" stroke="rgba(255,255,255,.25)" stroke-width="6" stroke-linecap="round"/>
  <line x1="400" y1="156" x2="400" y2="250" stroke="rgba(255,255,255,.3)"  stroke-width="7" stroke-linecap="round"/>
  <line x1="520" y1="170" x2="520" y2="250" stroke="rgba(255,255,255,.25)" stroke-width="6" stroke-linecap="round"/>
  <text x="400" y="330" font-family="sans-serif" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">200K+ helped · 87% satisfaction</text>''',

'Physical Hardware': '''
  <rect x="180" y="100" width="440" height="240" rx="8" fill="rgba(0,0,0,.3)" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
  <rect x="200" y="120" width="60"  height="60"  rx="4" fill="rgba(255,255,255,.15)" stroke="rgba(255,255,255,.2)" stroke-width="1"/>
  <rect x="310" y="120" width="80"  height="80"  rx="4" fill="rgba(255,255,255,.2)"  stroke="rgba(255,255,255,.3)" stroke-width="1.5"/>
  <rect x="450" y="130" width="50"  height="50"  rx="4" fill="rgba(255,255,255,.12)" stroke="rgba(255,255,255,.18)" stroke-width="1"/>
  <rect x="550" y="120" width="50"  height="70"  rx="4" fill="rgba(255,255,255,.15)" stroke="rgba(255,255,255,.2)" stroke-width="1"/>
  <line x1="260" y1="150" x2="310" y2="160" stroke="rgba(255,255,255,.25)" stroke-width="1.5"/>
  <line x1="390" y1="160" x2="450" y2="155" stroke="rgba(255,255,255,.25)" stroke-width="1.5"/>
  <line x1="500" y1="155" x2="550" y2="155" stroke="rgba(255,255,255,.25)" stroke-width="1.5"/>
  <text x="350" y="162" font-family="monospace" font-size="13" text-anchor="middle" fill="rgba(255,255,255,.6)">NPU</text>
  <text x="400" y="310" font-family="monospace" font-size="11" text-anchor="middle" fill="rgba(255,255,255,.4)">100 TOPS · 5W · Edge AI</text>''',
}


def make_product_svg(product: dict) -> str:
    """Generate a beautiful 800×450 SVG product image."""
    import re as _re
    mid   = _e(product.get('market_id', ''))
    name  = _e(product.get('name', '?'))[:32]
    cat   = _e(product.get('category', ''))
    grad  = product.get('gradient', 'linear-gradient(135deg,#667eea,#764ba2)')
    price = product.get('price', 0)
    rating = product.get('rating', 0)
    seller = _e(product.get('seller', ''))[:25]
    acc   = _e(product.get('accuracy', ''))

    colors = _re.findall(r'#[0-9a-fA-F]{3,6}', grad)
    c1 = colors[0] if colors else '#7c3aed'
    c2 = colors[1] if len(colors) > 1 else '#2563eb'

    illustration = _CAT_ART.get(product.get('category',''), '''
      <circle cx="400" cy="200" r="80" fill="rgba(255,255,255,.12)" stroke="rgba(255,255,255,.2)" stroke-width="2"/>
      <text x="400" y="215" font-family="serif" font-size="60" text-anchor="middle" fill="rgba(255,255,255,.8)">⚡</text>
    ''')

    stars = '★' * int(float(rating)) + ('☆' * (5 - int(float(rating))))
    price_str = f'${price:.0f}/mo' if price > 0 else 'Free'

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450" width="800" height="450">
  <defs>
    <linearGradient id="bg-{mid}" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="{c1}"/>
      <stop offset="100%" stop-color="{c2}"/>
    </linearGradient>
    <linearGradient id="overlay-{mid}" x1="0" y1="0" x2="0" y2="1">
      <stop offset="40%" stop-color="rgba(0,0,0,0)" stop-opacity="0"/>
      <stop offset="100%" stop-color="rgba(0,0,0,0.75)" stop-opacity="1"/>
    </linearGradient>
    <filter id="blur-{mid}"><feGaussianBlur stdDeviation="0.5"/></filter>
  </defs>

  <!-- Background gradient -->
  <rect width="800" height="450" fill="url(#bg-{mid})"/>

  <!-- Subtle dot pattern -->
  <pattern id="dots-{mid}" x="0" y="0" width="30" height="30" patternUnits="userSpaceOnUse">
    <circle cx="15" cy="15" r="1" fill="rgba(255,255,255,0.06)"/>
  </pattern>
  <rect width="800" height="450" fill="url(#dots-{mid})"/>

  <!-- Category illustration -->
  {illustration}

  <!-- Bottom gradient overlay for text readability -->
  <rect width="800" height="450" fill="url(#overlay-{mid})"/>

  <!-- Market ID badge (top left) -->
  <rect x="16" y="14" width="108" height="24" rx="12" fill="rgba(0,0,0,.4)"/>
  <text x="24" y="30" font-family="monospace" font-size="11" font-weight="700" fill="rgba(255,255,255,.75)">{mid}</text>

  <!-- Price badge (top right) -->
  <rect x="672" y="14" width="112" height="24" rx="12" fill="rgba(0,0,0,.4)"/>
  <text x="728" y="30" font-family="Inter,sans-serif" font-size="12" font-weight="800" fill="rgba(255,255,255,.9)" text-anchor="middle">{price_str}</text>

  <!-- Product name -->
  <text x="24" y="395" font-family="Inter,sans-serif" font-size="22" font-weight="900" fill="white" filter="url(#blur-{mid})" opacity="0.3">{name}</text>
  <text x="24" y="394" font-family="Inter,sans-serif" font-size="22" font-weight="900" fill="white">{name}</text>

  <!-- Category label -->
  <text x="24" y="418" font-family="Inter,sans-serif" font-size="13" fill="rgba(255,255,255,0.65)">{cat}</text>

  <!-- Stars + seller (bottom right) -->
  <text x="776" y="418" font-family="Inter,sans-serif" font-size="13" fill="rgba(255,200,50,.85)" text-anchor="end">{stars} {rating}</text>
  <text x="776" y="395" font-family="Inter,sans-serif" font-size="11" fill="rgba(255,255,255,.45)" text-anchor="end">{seller}</text>
</svg>'''


def _e(text):
    return str(text or '').replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('"','&quot;').replace("'",'&#39;')

def _stars(r):
    r = float(r or 0)
    return '★' * int(r) + ('½' if r % 1 >= 0.5 else '') + '☆' * (5 - int(r) - (1 if r%1>=0.5 else 0))

def _gradient_first(grad):
    """Extract first color from gradient string for simple use."""
    import re
    m = re.search(r'#[0-9a-fA-F]{3,6}', grad)
    return m.group() if m else '#7c3aed'


# ── Per-product CSS ────────────────────────────────────────────────────────────
def make_style(product):
    grad  = product.get('gradient', 'linear-gradient(135deg,#667eea,#764ba2)')
    color = _gradient_first(grad)
    return f"""\
/* style.css — {product['market_id']} */
:root {{
  --grad:   {grad};
  --color:  {color};
  --bg:     #05050f;
  --surf:   rgba(255,255,255,0.04);
  --border: rgba(255,255,255,0.08);
  --text:   #f1f5f9;
  --muted:  #64748b;
  --sec:    #94a3b8;
  --r:      16px;
  --t:      .28s cubic-bezier(.4,0,.2,1);
}}
*,*::before,*::after{{margin:0;padding:0;box-sizing:border-box}}
html{{scroll-behavior:smooth}}
body{{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden}}

/* back bar */
.back-bar{{position:fixed;top:0;left:0;right:0;z-index:100;height:54px;
  display:flex;align-items:center;padding:0 1.5rem;gap:1rem;
  background:rgba(5,5,15,.8);backdrop-filter:blur(20px);
  border-bottom:1px solid var(--border)}}
.back-bar a{{color:var(--sec);text-decoration:none;font-size:.85rem;font-weight:600;
  display:flex;align-items:center;gap:.4rem;transition:color var(--t)}}
.back-bar a:hover{{color:var(--text)}}
.back-bar .mid-pill{{margin-left:auto;background:rgba(255,255,255,.07);
  border:1px solid var(--border);border-radius:100px;padding:.25rem .85rem;
  font-size:.72rem;font-weight:800;letter-spacing:.08em;color:var(--muted)}}

/* hero */
.hero{{position:relative;min-height:65vh;display:flex;align-items:center;
  justify-content:center;padding:6rem 2rem 3rem;overflow:hidden;text-align:center}}
.hero-bg{{position:absolute;inset:0;background:var(--grad);opacity:.1}}
.hero-orb{{position:absolute;width:600px;height:600px;border-radius:50%;
  background:var(--grad);filter:blur(130px);opacity:.2;top:-150px;right:-200px;
  animation:float 7s ease-in-out infinite}}
canvas#c{{position:absolute;inset:0;opacity:.45}}
.hero-inner{{position:relative;z-index:2;max-width:800px;width:100%}}
.mid-badge{{display:inline-flex;align-items:center;gap:.5rem;margin-bottom:1.5rem;
  background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.14);
  border-radius:100px;padding:.35rem 1rem;font-size:.72rem;font-weight:800;
  color:rgba(255,255,255,.6);letter-spacing:.1em}}
.dot{{width:6px;height:6px;border-radius:50%;background:#34d399;animation:blink 1.4s infinite}}
.avatar{{width:90px;height:90px;border-radius:22px;background:var(--grad);
  display:flex;align-items:center;justify-content:center;font-size:2.5rem;
  font-weight:900;color:#fff;margin:0 auto 1.5rem;
  box-shadow:0 20px 60px rgba(0,0,0,.4);animation:float 4s ease-in-out infinite}}
.cat-pill{{display:inline-block;background:rgba(255,255,255,.1);border-radius:100px;
  padding:.28rem .9rem;font-size:.75rem;font-weight:700;
  letter-spacing:.08em;text-transform:uppercase;margin-bottom:.75rem}}
h1{{font-size:clamp(2rem,6vw,3.5rem);font-weight:900;line-height:1.1;margin-bottom:.75rem}}
.hero-short{{font-size:1.05rem;color:rgba(255,255,255,.72);margin-bottom:2rem;line-height:1.7}}
.hero-btns{{display:flex;gap:.75rem;justify-content:center;flex-wrap:wrap}}
.btn{{display:inline-flex;align-items:center;gap:.5rem;padding:.7rem 1.75rem;
  border-radius:100px;font-size:.875rem;font-weight:700;cursor:pointer;
  border:none;font-family:inherit;transition:var(--t);text-decoration:none}}
.btn-buy{{background:#fff;color:#1a1a35}}
.btn-buy:hover{{transform:translateY(-2px);box-shadow:0 8px 30px rgba(0,0,0,.3)}}
.btn-sound{{background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.2);color:#fff}}
.btn-sound:hover,.btn-sound.playing{{background:rgba(16,185,129,.25);border-color:#34d399}}
.btn-outline{{background:transparent;border:1px solid rgba(255,255,255,.3);color:#fff}}
.btn-outline:hover{{background:rgba(255,255,255,.08)}}

/* body */
.body{{max-width:960px;margin:0 auto;padding:3rem 1.5rem 5rem}}
.stats-row{{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:2.5rem}}
.stat-box{{background:var(--surf);border:1px solid var(--border);border-radius:var(--r);
  padding:1.25rem;text-align:center}}
.sv{{font-size:1.35rem;font-weight:900;display:block;margin-bottom:.2rem;
  background:var(--grad);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}}
.sl{{font-size:.68rem;color:var(--muted);text-transform:uppercase;letter-spacing:.07em}}
.tags{{display:flex;flex-wrap:wrap;gap:.4rem;margin-bottom:2rem}}
.tag{{background:rgba(124,58,237,.13);color:#a78bfa;border:1px solid rgba(124,58,237,.25);
  padding:.2rem .65rem;border-radius:100px;font-size:.7rem;font-weight:600}}
.sec{{margin-bottom:2.5rem}}
.sec-title{{font-size:.7rem;font-weight:800;text-transform:uppercase;letter-spacing:.12em;
  color:var(--muted);margin-bottom:1rem;display:flex;align-items:center;gap:.6rem}}
.sec-title::after{{content:'';flex:1;height:1px;background:var(--border)}}
.desc{{font-size:.95rem;color:var(--sec);line-height:1.85}}
.specs{{width:100%;border-collapse:collapse}}
.specs tr{{border-bottom:1px solid var(--border)}}
.specs td{{padding:.8rem 1rem;font-size:.875rem}}
.specs td:first-child{{color:var(--muted);width:38%}}
.specs td:last-child{{color:var(--text);font-weight:600}}
.seller-card{{background:var(--surf);border:1px solid var(--border);border-radius:var(--r);
  padding:1.4rem;display:flex;align-items:center;gap:1rem}}
.s-av{{width:46px;height:46px;border-radius:50%;background:var(--grad);
  display:flex;align-items:center;justify-content:center;
  font-weight:800;font-size:.85rem;color:#fff;flex-shrink:0}}
.s-name{{font-weight:700;margin-bottom:.2rem}}
.s-ver{{font-size:.72rem;color:#34d399}}
.s-unv{{font-size:.72rem;color:var(--muted)}}
.buy-section{{background:var(--surf);border:1px solid var(--border);border-radius:var(--r);
  padding:2rem;text-align:center;margin-top:2rem}}
.price{{font-size:3rem;font-weight:900;background:var(--grad);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}}
.per{{color:var(--muted);font-size:.875rem;margin-bottom:1.5rem}}
.buy-full{{width:100%;padding:1rem;border-radius:var(--r);background:var(--grad);
  border:none;color:#fff;font-size:1rem;font-weight:800;cursor:pointer;
  font-family:inherit;transition:var(--t)}}
.buy-full:hover{{transform:translateY(-2px);box-shadow:0 8px 30px rgba(0,0,0,.3)}}
footer{{text-align:center;padding:2rem;font-size:.78rem;color:var(--muted);
  border-top:1px solid var(--border)}}

/* sound wave */
.wave{{display:inline-flex;align-items:center;gap:2px;height:14px}}
.wave span{{display:block;width:3px;border-radius:3px;background:currentColor;
  animation:wave 1.2s ease-in-out infinite}}
.wave span:nth-child(1){{height:5px;animation-delay:0s}}
.wave span:nth-child(2){{height:14px;animation-delay:.12s}}
.wave span:nth-child(3){{height:8px;animation-delay:.24s}}
.wave span:nth-child(4){{height:11px;animation-delay:.36s}}
.wave span:nth-child(5){{height:4px;animation-delay:.48s}}

@keyframes float{{0%,100%{{transform:translateY(0)}}50%{{transform:translateY(-12px)}}}}
@keyframes blink{{0%,100%{{opacity:1}}50%{{opacity:.25}}}}
@keyframes wave{{0%,100%{{transform:scaleY(.35)}}50%{{transform:scaleY(1)}}}}
@keyframes fadeUp{{from{{opacity:0;transform:translateY(20px)}}to{{opacity:1;transform:none}}}}

.afu{{animation:fadeUp .6s ease both}}

@media(max-width:640px){{
  .stats-row{{grid-template-columns:repeat(2,1fr)}}
  h1{{font-size:2rem}} .price{{font-size:2rem}}
  .hero-btns{{flex-direction:column;align-items:center}}
}}
"""


# ── Per-product JS ─────────────────────────────────────────────────────────────
def make_script(product):
    mid     = product['market_id']
    name    = product['name'].replace("'", "\\'")
    short   = product.get('short_description','').replace("'","\\'")
    cat     = product.get('category','').replace("'","\\'")
    price   = float(product.get('price',0))
    billing = product.get('billing','monthly').replace("'","\\'")
    acc     = str(product.get('accuracy','N/A')).replace("'","\\'")
    speech  = f"{name}. {short}. Category: {cat}. Price: {price} dollars per {billing}. Accuracy: {acc}."
    return f"""\
/* script.js — {mid} */

// ── Particle canvas ──
(function(){{
  const cv=document.getElementById('c'), ctx=cv.getContext('2d');
  let W=0,H=0,pts=[];
  function resize(){{
    W=cv.width=window.innerWidth;
    H=cv.height=Math.max(window.innerHeight,cv.parentElement.clientHeight||0);
  }}
  function init(){{
    pts=Array.from({{length:70}},()=>({{
      x:Math.random()*W,y:Math.random()*H,
      r:Math.random()*1.8+.5,
      vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35,
      hue:200+Math.random()*80
    }}));
  }}
  function draw(){{
    ctx.clearRect(0,0,W,H);
    for(let i=0;i<pts.length;i++){{
      for(let j=i+1;j<pts.length;j++){{
        const dx=pts[i].x-pts[j].x,dy=pts[i].y-pts[j].y,d=Math.hypot(dx,dy);
        if(d<130){{
          ctx.beginPath();ctx.moveTo(pts[i].x,pts[i].y);ctx.lineTo(pts[j].x,pts[j].y);
          ctx.strokeStyle=`hsla(${{pts[i].hue}},85%,68%,${{(1-d/130)*.4}})`;
          ctx.lineWidth=.65;ctx.stroke();
        }}
      }}
      ctx.beginPath();ctx.arc(pts[i].x,pts[i].y,pts[i].r,0,Math.PI*2);
      ctx.fillStyle=`hsl(${{pts[i].hue}},85%,68%)`;ctx.fill();
      pts[i].x+=pts[i].vx;pts[i].y+=pts[i].vy;
      if(pts[i].x<0||pts[i].x>W)pts[i].vx*=-1;
      if(pts[i].y<0||pts[i].y>H)pts[i].vy*=-1;
    }}
    requestAnimationFrame(draw);
  }}
  window.addEventListener('resize',()=>{{resize();init();}});
  requestAnimationFrame(()=>requestAnimationFrame(()=>{{resize();init();draw();}}));
}})();

// ── Sound ──
const SPEECH_TEXT = '{speech}';
let _speaking=false;

function toggleSpeak(){{
  const btn=document.getElementById('sound-btn');
  if(_speaking){{
    speechSynthesis.cancel();_speaking=false;
    btn.innerHTML='🔊 Listen';btn.classList.remove('playing');return;
  }}
  if(!('speechSynthesis' in window)){{alert('TTS not supported in this browser.');return;}}
  const u=new SpeechSynthesisUtterance(SPEECH_TEXT);
  u.rate=0.92;u.pitch=1.05;
  u.onstart=()=>{{
    _speaking=true;btn.classList.add('playing');
    btn.innerHTML='⏹ Stop <span class="wave"><span></span><span></span><span></span><span></span><span></span></span>';
  }};
  u.onend=u.onerror=()=>{{_speaking=false;btn.classList.remove('playing');btn.innerHTML='🔊 Listen';}};
  speechSynthesis.speak(u);
}}

// ── Buy button ──
function goBuy(){{window.location.href='{SERVER}/payment/{mid}';}}

// ── Animate on scroll ──
const observer=new IntersectionObserver(entries=>{{
  entries.forEach(e=>{{if(e.isIntersecting)e.target.classList.add('afu')}});
}},{{threshold:.15}});
document.querySelectorAll('.stat-box,.sec,.seller-card,.buy-section').forEach(el=>{{
  el.style.opacity=0;observer.observe(el);
}});
"""


# ── Per-product HTML ───────────────────────────────────────────────────────────
def make_html(product):
    mid      = product['market_id']
    name     = _e(product['name'])
    cat      = _e(product['category'])
    short    = _e(product.get('short_description',''))
    desc     = _e(product.get('description','') or short)
    price    = float(product.get('price',0))
    rating   = float(product.get('rating',0))
    billing  = _e(product.get('billing','monthly'))
    seller   = _e(product.get('seller',''))
    params   = _e(product.get('parameters','N/A'))
    accuracy = _e(product.get('accuracy','N/A'))
    rtime    = _e(product.get('response_time','N/A'))
    downloads= int(product.get('downloads',0))
    rev_cnt  = int(product.get('review_count',0))
    lic      = _e(product.get('license','Commercial'))
    verified = product.get('seller_verified',False)
    tags     = product.get('tags',[])
    letter   = name[0] if name else '?'
    av_init  = str(product.get('seller_avatar','S') or 'S')[:2]
    stars    = _stars(rating)
    price_str= f'${price:.0f}' if price > 0 else 'Free'
    billing_str = f'/{billing}' if price > 0 else ''

    tags_html = ''.join(f'<span class="tag">{_e(t)}</span>' for t in tags[:8])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{name} · {mid} — Smart World Market</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<!-- Back bar -->
<div class="back-bar">
  <a href="{SERVER}">← Smart World Market</a>
  <a href="{SERVER}/vitrin">Vitrin</a>
  <a href="{SERVER}/product/{mid}">Full Details</a>
  <span class="mid-pill">{mid}</span>
</div>

<!-- Hero -->
<section class="hero">
  <div class="hero-bg"></div>
  <div class="hero-orb"></div>
  <canvas id="c"></canvas>
  <div class="hero-inner">
    <div class="mid-badge"><div class="dot"></div> MARKET ID: {mid}</div>
    <div class="avatar">{letter}</div>
    <div class="cat-pill">{cat}</div>
    <h1>{name}</h1>
    <p class="hero-short">{short}</p>
    <div class="hero-btns">
      <button class="btn btn-sound" id="sound-btn" onclick="toggleSpeak()">🔊 Listen</button>
      <button class="btn btn-buy" onclick="goBuy()">🚀 Buy — {price_str}{billing_str}</button>
      <a class="btn btn-outline" href="{SERVER}/product/{mid}">Full Details</a>
    </div>
  </div>
</section>

<!-- Body -->
<div class="body">

  <!-- Stats -->
  <div class="stats-row">
    <div class="stat-box"><span class="sv">{rating}</span><span class="sl">Rating ({rev_cnt} reviews)</span></div>
    <div class="stat-box"><span class="sv">{params}</span><span class="sl">Parameters</span></div>
    <div class="stat-box"><span class="sv">{accuracy}</span><span class="sl">Accuracy</span></div>
    <div class="stat-box"><span class="sv">{downloads:,}</span><span class="sl">Downloads</span></div>
  </div>

  <!-- Tags -->
  <div class="tags">{tags_html}</div>

  <!-- Description -->
  <div class="sec">
    <div class="sec-title">📖 About</div>
    <p class="desc">{desc}</p>
  </div>

  <!-- Specs -->
  <div class="sec">
    <div class="sec-title">⚙️ Specifications</div>
    <table class="specs">
      <tr><td>Market ID</td><td>{mid}</td></tr>
      <tr><td>Category</td><td>{cat}</td></tr>
      <tr><td>Parameters</td><td>{params}</td></tr>
      <tr><td>Accuracy</td><td>{accuracy}</td></tr>
      <tr><td>Response Time</td><td>{rtime}</td></tr>
      <tr><td>API Calls/Month</td><td>{product.get('api_calls_per_month',10000):,}</td></tr>
      <tr><td>License</td><td>{lic}</td></tr>
    </table>
  </div>

  <!-- Seller -->
  <div class="sec">
    <div class="sec-title">👤 Seller</div>
    <div class="seller-card">
      <div class="s-av">{av_init}</div>
      <div>
        <div class="s-name">{seller}</div>
        {'<div class="s-ver">✓ Verified Seller</div>' if verified else '<div class="s-unv">Community Seller</div>'}
      </div>
    </div>
  </div>

  <!-- Buy -->
  <div class="buy-section">
    <div class="price">{price_str}</div>
    <div class="per">per {billing} · {lic} license</div>
    <button class="buy-full" onclick="goBuy()">🔒 Purchase Access — {name}</button>
  </div>
</div>

<footer>Smart World Market AI Marketplace · {mid} · World's First AI Model Marketplace · © 2026</footer>

<script src="script.js"></script>
</body>
</html>"""


# ── Public API ─────────────────────────────────────────────────────────────────
def generate_product_page_to_disk(product):
    mid    = product['market_id']
    folder = os.path.join(MARKET_DIR, mid)
    os.makedirs(folder, exist_ok=True)
    with open(os.path.join(folder, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(make_html(product))
    with open(os.path.join(folder, 'style.css'), 'w', encoding='utf-8') as f:
        f.write(make_style(product))
    with open(os.path.join(folder, 'script.js'), 'w', encoding='utf-8') as f:
        f.write(make_script(product))


def generate_all(skip_existing=False):
    """Generate market pages. skip_existing=True for fast startup."""
    os.makedirs(MARKET_DIR, exist_ok=True)
    products = get_all_products()
    new_count = 0
    for p in products:
        mid    = p['market_id']
        folder = os.path.join(MARKET_DIR, mid)
        if skip_existing and os.path.isfile(os.path.join(folder, 'index.html')):
            continue
        generate_product_page_to_disk(p)
        new_count += 1
    if new_count:
        print(f'[Market] Generated {new_count} page(s).')
    else:
        print('[Market] All market pages are up to date.')


if __name__ == '__main__':
    from database import init_db
    init_db()
    generate_all()
